// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// gemCpp
List gemCpp(List dList, CharacterVector met);
RcppExport SEXP pirate_gemCpp(SEXP dListSEXP, SEXP metSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< List >::type dList(dListSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type met(metSEXP);
    rcpp_result_gen = Rcpp::wrap(gemCpp(dList, met));
    return rcpp_result_gen;
END_RCPP
}
