// This file was generated by Rcpp::compileAttributes
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <RcppArmadillo.h>
#include <Rcpp.h>

using namespace Rcpp;

// gemCpp
List gemCpp(List dList, CharacterVector met);
RcppExport SEXP GEM_gemCpp(SEXP dListSEXP, SEXP metSEXP) {
BEGIN_RCPP
    Rcpp::RObject __result;
    Rcpp::RNGScope __rngScope;
    Rcpp::traits::input_parameter< List >::type dList(dListSEXP);
    Rcpp::traits::input_parameter< CharacterVector >::type met(metSEXP);
    __result = Rcpp::wrap(gemCpp(dList, met));
    return __result;
END_RCPP
}
